# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  haml-predictor:
    environment:
      - LOG_LEVEL=WARNING
      - ENVIRONMENT=production
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
    healthcheck:
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  timescaledb:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5  # More secure auth in production
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  mosquitto:
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  redis:
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --requirepass ${REDIS_PASSWORD:-changeme}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.2'
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3