# Prometheus configuration for Home Assistant ML Predictor monitoring

global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: 'haml-predictor'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Home Assistant ML Predictor Application
  - job_name: 'haml-predictor'
    static_configs:
      - targets: ['haml-predictor:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http

  # TimescaleDB/PostgreSQL
  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:5432']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scheme: http

  # MQTT Broker (if metrics are enabled)
  - job_name: 'mosquitto'
    static_configs:
      - targets: ['mosquitto:1883']
    scrape_interval: 60s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (if available on host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 15d
    retention.size: 1GB