# Main configuration file for Occupancy Prediction System
home_assistant:
  url: "http://192.168.51.247:8123"
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjMTU0OGJjODJlZWY0Nzg0YjRlNjc2Mjc2NDRhZGQyYSIsImlhdCI6MTc1Mjk0ODUxMCwiZXhwIjoyMDY4MzA4NTEwfQ.4nkpClh-UnOhQRkPgZjOG0NKkNtiLPZsXWKmY20czO0"
  websocket_timeout: 30
  api_timeout: 10

database:
  connection_string: "postgresql://occupancy_user:occupancy_pass@localhost:5432/occupancy_prediction"
  pool_size: 10
  max_overflow: 20
  
mqtt:
  broker: "localhost"  # Will be updated when provided
  port: 1883
  username: ""
  password: ""
  topic_prefix: "occupancy/predictions"

prediction:
  interval_seconds: 300  # 5 minutes
  accuracy_threshold_minutes: 15
  confidence_threshold: 0.7
  
logging:
  level: "INFO"
  format: "structured"
  
features:
  lookback_hours: 24
  sequence_length: 50
  temporal_features: true
  sequential_features: true
  contextual_features: true